"""empty message

Revision ID: 875ed4281cd0
Revises: bf5d42e4732b
Create Date: 2020-05-01 17:24:10.865443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '875ed4281cd0'
down_revision = 'bf5d42e4732b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'show', 'venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.drop_column('show', 'venue_id')
    # ### end Alembic commands ###
